// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA597Ui3sZCjXbBdzHW7niyW573RmJSnMo',
    appId: '1:730877406064:web:6961a1e5c41e83844dfdb5',
    messagingSenderId: '730877406064',
    projectId: 'meto-fb8b5',
    authDomain: 'meto-fb8b5.firebaseapp.com',
    storageBucket: 'meto-fb8b5.firebasestorage.app',
    measurementId: 'G-80MN09Z4WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbKJVr0CZFXPgzxA6m6fOnUmbGq3LwFHs',
    appId: '1:730877406064:android:18a6c17ecd534e214dfdb5',
    messagingSenderId: '730877406064',
    projectId: 'meto-fb8b5',
    storageBucket: 'meto-fb8b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFepOaRz08U4-dc9Xg1mhlKAGU0hMcdN4',
    appId: '1:730877406064:ios:6dde111c0d8c84314dfdb5',
    messagingSenderId: '730877406064',
    projectId: 'meto-fb8b5',
    storageBucket: 'meto-fb8b5.firebasestorage.app',
    iosBundleId: 'com.meto.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFepOaRz08U4-dc9Xg1mhlKAGU0hMcdN4',
    appId: '1:730877406064:ios:1f7dc86e2c8b4c2a4dfdb5',
    messagingSenderId: '730877406064',
    projectId: 'meto-fb8b5',
    storageBucket: 'meto-fb8b5.firebasestorage.app',
    iosBundleId: 'com.example.metoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA597Ui3sZCjXbBdzHW7niyW573RmJSnMo',
    appId: '1:730877406064:web:d862293eb5666ad04dfdb5',
    messagingSenderId: '730877406064',
    projectId: 'meto-fb8b5',
    authDomain: 'meto-fb8b5.firebaseapp.com',
    storageBucket: 'meto-fb8b5.firebasestorage.app',
    measurementId: 'G-QLXQFQFZYG',
  );
}
